---
- hosts: yum
  become: true
  become_method: sudo
  tasks: 
      - name: Update Repository cache
        become: true
        yum:
          name: '*'
          state: latest
          update_cache: yes
...